--------------------------------------------------------------------------------
/*Tablas*/
--------------------------------------------------------------------------------
/*Tabla Categoria*/
CREATE TABLE CATEGORIA (ID_CATEGORIA NUMBER(10) NOT NULL, CODIGO_CATEGORIA NUMBER(10) NOT NULL, 
NOMBRE_CATEGORIA VARCHAR2(200) NOT NULL, DESRIPCION_CATEGORIA VARCHAR2(200) NOT NULL, 
ESTADO VARCHAR2(20) NOT NULL,
CONSTRAINT CATEGORIA_PK PRIMARY KEY (ID_CATEGORIA));

/*Tabla Producto*/
CREATE TABLE PRODUCTO (ID_PRODUCTO NUMBER(10) NOT NULL, CODIGO_PRODUCTO NUMBER(10) NOT NULL, 
ID_CATEGORIA NUMBER NOT NULL, NOMBRE_PRODUCTO VARCHAR2(200) NOT NULL, 
DESRIPCION_PRODUCTO VARCHAR2(200) NOT NULL, MATERIAL VARCHAR2(100) NOT NULL, ESTADO VARCHAR2(20) NOT NULL,
CONSTRAINT PRODUCTO_PK PRIMARY KEY (ID_PRODUCTO),
CONSTRAINT FK_CATEGORIA FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA (ID_CATEGORIA));

/*Tabla Inventario*/
CREATE TABLE INVENTARIO (INVENTARIO_ID NUMBER(10) NOT NULL, PRODUCTO_ID NUMBER(10) NOT NULL,
TALLA VARCHAR2(50), COLOR VARCHAR2(50) NOT NULL, STOCK_ACTUAL NUMBER(10) NOT NULL,
STOCK_MINIMO NUMBER(10) NOT NULL, PRECIO_VENTA NUMBER(10,2) NOT NULL,
CONSTRAINT INVENTARIO_PK PRIMARY KEY (INVENTARIO_ID),
CONSTRAINT FK_INVENTARIO FOREIGN KEY (PRODUCTO_ID)REFERENCES PRODUCTO (ID_PRODUCTO));

/*Tabla Proveedor*/
CREATE TABLE PROVEEDOR (ID_PROVEEDOR NUMBER(10) NOT NULL, CEDULA VARCHAR2(20) NOT NULL, 
NOMBRE VARCHAR2(100) NOT NULL, APELLIDOS VARCHAR2(100) NOT NULL, EMAIL VARCHAR2(100), 
TELEFONO VARCHAR2(20), DIRECCION VARCHAR2(200), ESTADO VARCHAR2(20) NOT NULL,
CONSTRAINT PROVEEDOR_PK PRIMARY KEY (ID_PROVEEDOR));

/*Tabla Producto_Proveedor*/
CREATE TABLE PRODUCTO_PROVEEDOR (PRODUCTO_PROVEEDOR_ID NUMBER(10) NOT NULL, PRODUCTO_ID NUMBER(10) NOT NULL, 
PROVEEDOR_ID NUMBER(10) NOT NULL, PRECIO_COMPRA NUMBER(10,2) NOT NULL, ESTADO VARCHAR2(20) NOT NULL,
CONSTRAINT PRODUCTO_PROVEEDOR_PK PRIMARY KEY (PRODUCTO_PROVEEDOR_ID),
CONSTRAINT FK_PRODUCTO FOREIGN KEY (PRODUCTO_ID) REFERENCES PRODUCTO (ID_PRODUCTO),
CONSTRAINT FK_PROVEEDOR FOREIGN KEY (PROVEEDOR_ID) REFERENCES PROVEEDOR (ID_PROVEEDOR));

/*Tabla Cliente*/
CREATE TABLE CLIENTE (ID_CLIENTE NUMBER(10) NOT NULL, CEDULA VARCHAR2(20) NOT NULL, NOMBRE VARCHAR2(100) NOT NULL,
APELLIDOS VARCHAR2(100) NOT NULL, EMAIL VARCHAR2(100), TELEFONO VARCHAR2(20), DIRECCION VARCHAR2(200),
CONTRASENA VARCHAR2(100), ESTADO VARCHAR2(20) NOT NULL,
CONSTRAINT CLIENTE_PK PRIMARY KEY (ID_CLIENTE));

/*Tabla Venta*/
CREATE TABLE VENTA (VENTA_ID NUMBER(10) NOT NULL, CODIGO_VENTA NUMBER(10) NOT NULL, CLIENTE_ID NUMBER(10) NOT NULL,
FECHA_VENTA DATE NOT NULL, SUBTOTAL NUMBER(10,2) NOT NULL, IMPUESTO NUMBER(10,2) NOT NULL, DESCUENTO NUMBER(10,2),
TOTAL NUMBER(10,2) NOT NULL, MEDIO_PAGO VARCHAR2(50) NOT  NULL, ESTADO VARCHAR2(20) NOT NULL,
CONSTRAINT VENTA_PK PRIMARY KEY (VENTA_ID),
CONSTRAINT FK_CLIENTE FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTE (ID_CLIENTE));

/*Tabla Detalle_Venta*/
CREATE TABLE DETALLE_VENTA (DETALLE_ID NUMBER(10) NOT NULL, VENTA_ID NUMBER(10) NOT NULL, 
INVENTARIO_ID NUMBER(10) NOT NULL, CANTIDAD NUMBER(10) NOT NULL, PRECIO_UNITARIO NUMBER(10,2) NOT NULL,
SUBTOTAL NUMBER(10,2) NOT NULL, DESCUENTO_ITEM NUMBER(10,2),
CONSTRAINT DETALLE_PK PRIMARY KEY (DETALLE_ID),
CONSTRAINT FK_VENTA_DETALLE FOREIGN KEY (VENTA_ID) REFERENCES VENTA (VENTA_ID),
CONSTRAINT FK_INVENTARIO_DETALLE FOREIGN KEY (INVENTARIO_ID) REFERENCES INVENTARIO (INVENTARIO_ID));

ALTER TABLE PRODUCTO ADD IMAGEN VARCHAR2(255);
--------------------------------------------------------------------------------
-- SECUENCIAS
--------------------------------------------------------------------------------
CREATE SEQUENCE producto_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE categoria_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE cliente_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE proveedor_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE venta_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE asociacion_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE detalle_venta_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE inventario_seq START WITH 1 INCREMENT BY 1;